"""posts

Revision ID: 875b3de0c0df
Revises: 94961ba8ba5a
Create Date: 2026-01-09 12:55:41.658190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875b3de0c0df'
down_revision = '94961ba8ba5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
