"""drivers and schools

Revision ID: 94961ba8ba5a
Revises: 
Create Date: 2026-01-09 12:50:10.468907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94961ba8ba5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('id_license', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('earning', sa.Float(), nullable=True),
    sa.Column('file_license', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', 'id_license')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('dominial_suffix', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools')
    op.drop_table('drivers')
    # ### end Alembic commands ###
